spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: WORDWEB
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.OracleDialect

jwt:
  secret: ${JWT_SECRET}

deepseek:
  api-key: ${DEEPSEEK_API_KEY}
  url: https://api.deepseek.com/v1/chat/completions
