spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: wordweb
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.OracleDialect

# JWT 설정
jwt:
  secret: ${JWT_SECRET}   # 환경변수로 넣기 (필수)

# DeepSeek 설정
deepseek:
  api-key: ${DEEPSEEK_API_KEY}   # 환경변수로 넣기
  url: https://api.deepseek.com/v1/chat/completions
